version: '3.8'

services:
  backend:
    container_name: tickets_booking_system-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      HTTP_PORT: ${HTTP_PORT}
      SOCK_PORT: ${SOCK_PORT}
      HOST: ${HOST}
      DB_PASSWRD: ${DB_PASSWRD}
      DB_USERNAME: ${DB_USERNAME}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3001:3001"
      - "3443:3443"
      - "4029:4029"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm run migration; npm run start"
    networks:
      - ticket_booking_network

  frontend:
    build:
      context: ./frontend/ticket-booking-system
      dockerfile: Dockerfile
    container_name: tickets_booking_system-frontend
    restart: unless-stopped
    environment:
      REACT_APP_SOCKET_URL: wss://192.168.1.10:3443
      REACT_APP_API_URL: https://192.168.1.10:3443/api
      HTTPS: "true"
      SSL_CRT_FILE: "/app/certs/cert.pem"
      SSL_KEY_FILE: "/app/certs/key.pem"
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/ticket-booking-system:/app
      - /app/node_modules
      - ./backend/cert.pem:/app/certs/cert.pem:ro   # <- монтируем cert
      - ./backend/key.pem:/app/certs/key.pem:ro
    command: npm start
    networks:
      - ticket_booking_network

  db:
    image: postgres:16.0
    container_name: tickets_booking_system-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWRD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      # Важно! Устанавливаем пользователя по умолчанию
      PGUSER: ${DB_USERNAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - ticket_booking_network

volumes:
  db-data:

networks:
  ticket_booking_network:
    driver: bridge